# Generated by Django 6.0.7 on 2026-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminPortal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledvisit",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                default=60, help_text="Estimated duration in minutes."
            ),
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="other_support_details",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="support_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="visit_purpose",
            field=models.CharField(
                choices=[
                    ("regular_check_in", "Regular Check-In"),
                    ("mobility", "Mobility Assistance"),
                    ("meal", "Meal Assistance"),
                    ("emotional", "Emotional Support"),
                    ("medical", "Medical Assistance"),
                    ("other", "Other"),
                ],
                default="regular_check_in",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="visit_type",
            field=models.CharField(
                choices=[("home_visit", "Home Visit"), ("phone_call", "Phone Call")],
                default="home_visit",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledvisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Upcoming"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled / Missed"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
