# Generated by Django 6.0.7 on 2026-07-29 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("senior", "Senior"),
                            ("guardian", "Guardian"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("nric_fin", models.CharField(max_length=20, unique=True)),
                ("mobile_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeniorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                ("unit_number", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("mandarin", "Mandarin"),
                            ("malay", "Malay"),
                            ("tamil", "Tamil"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("regular_check_ins", models.BooleanField(default=False)),
                ("mobility_assistance", models.BooleanField(default=False)),
                ("meal_assistance", models.BooleanField(default=False)),
                ("emotional_support", models.BooleanField(default=False)),
                ("medical_assistance", models.BooleanField(default=False)),
                ("other_support", models.CharField(blank=True, max_length=150)),
                (
                    "app_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senior_profile",
                        to="accounts.appuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("relationship", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=20)),
                (
                    "senior",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contact",
                        to="accounts.seniorprofile",
                    ),
                ),
            ],
        ),
    ]
