# Generated by Django 6.0.7 on 2026-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seniorprofile",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="medical_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="religion",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
