# Generated by Django 6.0.7 on 2026-08-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_seniorprofile_allergies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                ("unit_number", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("mandarin", "Mandarin"),
                            ("malay", "Malay"),
                            ("tamil", "Tamil"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("regular_check_ins", models.BooleanField(default=False)),
                ("mobility_assistance", models.BooleanField(default=False)),
                ("meal_assistance", models.BooleanField(default=False)),
                ("emotional_support", models.BooleanField(default=False)),
                ("medical_assistance", models.BooleanField(default=False)),
                ("other_support", models.CharField(blank=True, max_length=150)),
                ("transport_available", models.BooleanField(default=False)),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "app_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_profile",
                        to="accounts.appuser",
                    ),
                ),
            ],
        ),
    ]
