# Generated by Django 6.0.7 on 2026-08-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_seniorvolunteerassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="about_me",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="skills_interests",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="VolunteerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identification", "NRIC / Identification Card"),
                            ("first_aid", "First Aid Certificate"),
                            ("background", "Background Appointment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="volunteer_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.volunteerprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "document_type"),
                        name="unique_volunteer_document_type",
                    )
                ],
            },
        ),
    ]
