# Generated by Django 6.0.7 on 2026-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_volunteerprofile_about_me_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("senior", "Senior"),
                    ("guardian", "Guardian"),
                    ("volunteer", "Volunteer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
