# Generated by Django 6.0.7 on 2026-09-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_appuser_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationship_to_senior", models.CharField(blank=True, max_length=50)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Call"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("mandarin", "Mandarin"),
                            ("malay", "Malay"),
                            ("tamil", "Tamil"),
                            ("other", "Other"),
                        ],
                        default="english",
                        max_length=20,
                    ),
                ),
                (
                    "app_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_profile",
                        to="accounts.appuser",
                    ),
                ),
                (
                    "linked_senior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardians",
                        to="accounts.seniorprofile",
                    ),
                ),
            ],
        ),
    ]
