# Generated by Django 6.0.7 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_guardianprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
