# Generated by Django 6.0.7 on 2026-08-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_seniorprofile_allergies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellbeingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feeling",
                    models.CharField(
                        choices=[
                            ("great", "Great"),
                            ("good", "Good"),
                            ("okay", "Okay"),
                            ("not_good", "Not Good"),
                            ("need_support", "Need Support"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "senior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_submissions",
                        to="accounts.seniorprofile",
                    ),
                ),
            ],
        ),
    ]
