# Generated by Django 6.0.7 on 2026-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seniorPortal", "0002_supportrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellbeingsubmission",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellbeingsubmission",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
