# Generated by Django 6.0.7 on 2026-09-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminPortal", "0002_scheduledvisit_estimated_duration_and_more"),
        ("volunteerPortal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wellbeing_status",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("okay", "Okay"),
                            ("concern", "Concern"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assistance_provided", models.TextField()),
                ("observations", models.TextField(blank=True)),
                ("concerns", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_report",
                        to="adminPortal.scheduledvisit",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
